### ISSUE TITLE
No scroll during drag/drop

### ISSUE THREAD

**Issue by jaumard** [jaumard/ngx-dashboard#1]
Desktop or mobile doesn't scroll when drag

**Comment by nadir35** [comment]
Do you want drag scroll on desktop too? Because on desktop you can just scroll with mousewheel while dragging....
For touch devices I'm finalizing a solution right now.

**Comment by jaumard** [comment]
Hum normally on desktop it should already works (or it should) 
Nice thanks for the help ! :D

**Comment by jaumard** [comment]
Hum you're right doesn't seems to work on desktop too :( if you manage to also fix it for desktop it would be amazing :)

**Comment by nadir35** [comment]
Ok I think I have something that seems to work with mobile and desktop. For desktop it works with scroll via dragging and with mouse wheel. Can you try it out?

[dashboard.component.js.txt](https://github.com/jaumard/ngx-dashboard/files/986902/dashboard.component.js.txt)

**Comment by jaumard** [comment]
Cool I'll try that :) it may take some time because you edited the compiled JS so I need to find changes and apply then to the source TS file. I'll keep you updated thanks !

**Comment by nadir35** [comment]
Well all I can see in my /node-modules/ngx-dashboard/ are JS files, I dont have the source TS files. Or did you add them in the latest npm version?

**Comment by jaumard** [comment]
Right TS files are not publish into npm, only the final compiled version. TS versions are only in this repo for example the dashboard is here https://github.com/jaumard/ngx-dashboard/blob/master/src/components/dashboard/dashboard.component.ts

**Comment by jaumard** [comment]
I test your js version for now, look promising. On desktop it's working but maybe too sensible ? Is there a way to scroll more slowly than this ? Because we reach the end or start very quickly and if you want to set it in the middle it's more difficult. 

For mobile look like it work but on Android / Chrome sometime the scroll doesn't append at all but when it work it's perfect !

**Comment by nadir35** [comment]
the amount of scrolling is decided by the "15" in the _scrollDown and _scrollUp functions. Also you can play around with the delay.

If you could reproduce the "doesnt append" bug that would be nice.

**Comment by jaumard** [comment]
Ho ok I'll play with this thanks.
For the mobile bug I made a video, like this you can see, when the top bar is present the scroll doesn't append, but when it disappears then all is working fine. 

[device-2017-05-11-071224.mp4.zip](https://github.com/jaumard/ngx-dashboard/files/991938/device-2017-05-11-071224.mp4.zip)

**Comment by nadir35** [comment]
Hmmm, very interesting bug..... My guess would be that if the bar appears, it offsets screen.availHeight or something else which I use for my calculations, I am actually pretty sure about that. Can you try to reproduce the bug while scrolling up instead of down? I think it still works then.

**Comment by jaumard** [comment]
Scrolling up is still working when down is not you're right :)

**Comment by nadir35** [comment]
Can you try replacin the two occurences of `screen.availHeight` with `window.innerHeight` ? This should fix it for the URL bar, but I'm not sure if it will work correctly on iOS / Desktop afterwards.

**Comment by nadir35** [comment]
I tried it on my Android device, replacing` screen.availHeight` with `window.innerHeight` in the 2 occurences of dashboard.component.js as i mentioned above, and I think that it works both ways now. Can you please check?

**Comment by jaumard** [comment]
Look good on desktop and mobile (Android) don't have any iPhone to test. Nice job ! 
As there a lot of changes to make this work can you put them under the TS file ? Don't want to forgot some parts by doing a dif from JS version.
Thanks
https://github.com/jaumard/ngx-dashboard/blob/master/src/components/dashboard/dashboard.component.ts

**Comment by nadir35** [comment]
Nice. Please try this out, i also had to do it by dif from JS so there may be problems ^^
[dashboard.component.ts.txt](https://github.com/jaumard/ngx-dashboard/files/1004010/dashboard.component.ts.txt)

**Comment by jaumard** [comment]
Thanks I'll try it out ! At least it's simpler for you as you made the changes ^^ I'll let you know if there some trouble

**Comment by jaumard** [comment]
As I see it's perfect :) thanks a lot for the fix ! It's deploy on 1.1.4 let me know if there some problem
