### ISSUE TITLE
ngx-dashboard with card

### ISSUE THREAD

**Issue by kirtiesl** [jaumard/ngx-dashboard#12]
Unable to drag and drop card inside<widget> tag in ngx-dashboard. Please help....

**Comment by jaumard** [comment]
What do you mean by "inside tag" ?

**Comment by kirtiesl** [comment]
Here is my html - 
<dashboard (onOrderChange)="logOrder($event)" (onDragStart)="log($event, 'ondragstart')"
          (onDragEnd)="log($event, 'ondragend')"
          (onDrag)="log($event, 'ondragmove')" class="dashboard" 
          [margin]="dashboardMargin">
      <div *ngFor="let widget of widgetCount;let i=index;">
        <widget>
            <dynamic-component [componentData]="componentData[i]">
            </dynamic-component>
        </widget>
      </div>
</dashboard>

Inside <dynamic-component> i am having <md-card>. So, its working when clicked on <widget> but unable to drag and drop when clicked on card??

**Comment by jaumard** [comment]
You should take a look at the demo https://github.com/jaumard/ngx-dashboard/blob/master/demo/
More specifically to https://github.com/jaumard/ngx-dashboard/blob/master/demo/src/app/app.component.html you need to use a widget not a div

**Comment by kirtiesl** [comment]
yes taken look. Still unable to drag when clicked on card.
my Code rewritten - 
<dashboard (onOrderChange)="logOrder($event)" (onDragStart)="log($event, 'ondragstart')"
           (onDragEnd)="log($event, 'ondragend')"
           (onDrag)="log($event, 'ondragmove')" class="dashboard" [widgetsSize]="widgetsSize"
           [margin]="dashboardMargin">
    <widget [size]="[fxmd[i], fxxs[i]]" *ngFor="let widget of widgetCount;let i=index;">
      <dynamic-component  [componentData]="componentData[i]"></dynamic-component>
    </widget>
  </dashboard>
inside dynamic-component i have dynamically generated card. also I want to allocate widget size dynamically.

**Comment by jaumard** [comment]
Only widgets can be drag, and it will not work for sub component. Widgets should be direct children of dashboard tag

**Comment by kirtiesl** [comment]
ok . Thank you.
