### ISSUE TITLE
height is calculated in wrong way

### ISSUE THREAD

**Issue by michalkotas** [jaumard/ngx-dashboard#16]
height is calculated in wrong way.

How to reproduce:
modify demo app by setting 
this.widgetsSize[1] = 10 (in ts code)
dashboardMargin: number = 21 (in ts code)
[size]="[1, 4]" (in html)

Results:
widget height will be calculated wrongly - by adding multiple margin values.
for [size]="[1, 4]" it will give value 103 (10*4+21+21+21)

![image](https://user-images.githubusercontent.com/1055821/27349235-3b25bba0-55ff-11e7-803d-cb7da8ed227c.png)

**Comment by jaumard** [comment]
Hum I don't see anything wrong here. When you tell size = [1,2] you mean you want the height to be 2 block, but at the same time you want a margin between blocks of 21 so the actual height of the widget will be 10*2 + 21 so 41. If I don't add also the margin into the height then all widgets will not be aligned at all. 

So for me all good here as it's the behavior I want. But maybe I don't understand correctly @mikofoto ?

**Comment by michalkotas** [comment]
@jaumard please take a look on widgets bigger than 3 (height).

Example:
for [size]="[1, 4]" it will give value 103 (`10*4+21+21+21`), expected value is 82 (`10*4+21+21`)

**Comment by jaumard** [comment]
In fact it's 103 because you want 4 block so there 3 margins to fill, the one between 1-2, the one between 2-3 and the one between 3-4 looks right to me @mikofoto right?

**Comment by michalkotas** [comment]
I thought about it little bit more, and you are right. Additional margins are required to align with other widgets.

**Comment by jaumard** [comment]
Yes :) so all good here closing
