### ISSUE TITLE
'is not exported by' error when RollUp

### ISSUE THREAD

**Issue by cracrayol** [jaumard/ngx-dashboard#17]
I'm testing your component and it works well chen compiling my application in JIT or AOT without RollUp.

But when I'm trying to compiling it using AOT + Rollup, I've got this error : 

> { Error: 'DashboardComponent' is not exported by node_modules\ngx-dashboard\index.js
>     at error (***\front\node_modules\rollup\src\utils\error.js:2:14)
>     at Module.error$1 [as error] (***\front\node_modules\rollup\src\Module.js:303:2)
>     at Module.trace (***\front\node_modules\rollup\src\Module.js:400:10)
>     at ModuleScope.findDeclaration (***\front\node_modules\rollup\src\ast\scopes\ModuleScope.js:52:22)
>     at Identifier.bind (***\front\node_modules\rollup\src\ast\nodes\Identifier.js:22:29)
>     at ***\front\node_modules\rollup\src\ast\Node.js:6:34
>     at CallExpression.eachChild (***\front\node_modules\rollup\src\ast\Node.js:18:20)
>     at CallExpression.bind (***\front\node_modules\rollup\src\ast\Node.js:6:8)
>     at CallExpression.bind (***\front\node_modules\rollup\src\ast\nodes\CallExpression.js:26:13)
>     at ***\front\node_modules\rollup\src\ast\Node.js:6:34
>   code: 'MISSING_EXPORT',
>   url: 'https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module',
>   pos: 826,
>   loc: { file: '***\\front\\dist\\tmp\\app\\front\\***\\home\\home.component.js',
>   line: 11,
>   column: 9 },
>   frame: ' 9: };\n10: import { Component, ViewChild, HostListener } from \'@angular/core\';\n11: import { DashboardComponent } from \'ngx-dashboard\';\n             ^\n12: import * as W from \'./widgets/index\';\n13: let HomeComponent = class HomeComponent {' }

Do you know why this error happens ? Is it a problem with the ngx-dashboard component/module itself ?

**Comment by jaumard** [comment]
I don't know Rollup at all, never use it sorry :/ I suppose rollup is not happy with how I export classes from what the link say https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

**Comment by cracrayol** [comment]
Ok, i've solved the problem by using the full path of the module/component/directive instead of using only 'ngx-dashboard'.

For example :
```
import { WidgetHandleDirective, WidgetComponent } from 'ngx-dashboard';
```
became
```
import { WidgetHandleDirective } from 'ngx-dashboard/directives/widget-handle.directive';
import { WidgetComponent } from 'ngx-dashboard/components/widget/widget.component';
```

Perhaps change the path where is located the module because it's a little bit strange (`import { NgDashboardModule } from 'ngx-dashboard/components/index';`)

**Comment by jaumard** [comment]
Cool if you found a solution ! :) Strange that rollup doesn't like the way I export classes... Pretty basic export * from ....
