### ISSUE TITLE
how to run in angular 4

### ISSUE THREAD

**Issue by waleed-sarwar** [jaumard/ngx-dashboard#18]
hi,

i want to use this package in my angular 4 project but its not working
even i tried to run the demo but thats too not working 

can you help me to run this package

in demo it gives error no dist folder exists at the which is mention in code app.component.ts file

many thanks

**Comment by jaumard** [comment]
Hello,

For the demo it's a little bit tricky to make it run.
Here is what I did: 

```
cd ngx-dashboard
npm i 
npm run build
cd demo 
npm i
cd src
ln -s ../../src/dist/ .
cd ..
npm start
```

Let me know if it's ok now :)

**Comment by waleed-sarwar** [comment]
thanks it works
