### ISSUE TITLE
Add custom widget problem 

### ISSUE THREAD

**Issue by anvial** [jaumard/ngx-dashboard#19]
Hello, 

When I'm trying to use addWidget function in my project I get:  
![image](https://user-images.githubusercontent.com/1950326/28306683-ed6f1662-6ba8-11e7-9b8f-4c8afd0e9b21.png)

PS: angular 4, angular-cli project. 
PSS: I've added Component to declaration amd entryComponents of the main Module. 

Here si the code on custom component: 

import { Component, Renderer2, ElementRef, forwardRef, Input, ViewChild } from '@angular/core';
import { WidgetComponent, WidgetHandleDirective } from "ngx-dashboard";

const forwardReference = forwardRef(() => TestWidgetComponent);

@Component({
  selector: 'c2gui-test-widget',
  templateUrl: './test-widget.component.html',
  styleUrls: ['./test-widget.component.css'],
  providers: [{provide: WidgetComponent, useExisting: forwardReference}]
})
export class TestWidgetComponent extends WidgetComponent {

  @Input() public size: number[] = [1, 1];
  @Input() public widgetId: string;
  @ViewChild(WidgetHandleDirective) protected _handle: WidgetHandleDirective;

  constructor(
    ngEl: ElementRef,
    renderer: Renderer2
  ) {
    super(ngEl, renderer);
  }

}

Thank You!

**Comment by nadir35** [comment]
Can you post your main module? Your TestWidgetComponent should be in the declarations and entryComponents tag.

**Comment by jaumard** [comment]
You can check my implementation here 
https://github.com/mylisabox/lisa-ui/blob/master/src/app/components/widget/widget.component.ts#L26

And main module: 
https://github.com/mylisabox/lisa-ui/blob/master/src/app/app.module.ts#L91
https://github.com/mylisabox/lisa-ui/blob/master/src/app/app.module.ts#L68

At first look I don't find any problem with your widget class, but it doesn't look like a problem with ngx-dashboard, more something wrong with your configuration (app.module maybe)

**Comment by anvial** [comment]
Thanks for rapid response. 
Hm... I will now check your example . Thank You.

Here is my app.module.ts:

import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
...
import { TestWidgetComponent } from './components/main-page/widgets/test-widget/test-widget.component';


@NgModule({
  declarations: [
    ...
    TestWidgetComponent,
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    ...
  ],
  providers: [
    ...
  ],
  entryComponents: [
    ...
    TestWidgetComponent
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by anvial** [comment]
Hmmm... I don't find the difference in our modules... 

Could You, please, give an example of the component, where you call the "addWidget()"? 

Thank You.

**Comment by jaumard** [comment]
I add dynamically widget on this project ^^ (https://github.com/mylisabox/lisa-ui/blob/master/src/app/pages/home/home.component.ts#L296)

But the demo app also add widget dynamically, maybe it will be more simple  https://github.com/jaumard/ngx-dashboard/blob/master/demo/src/app/app.component.ts#L48 

Widget: https://github.com/jaumard/ngx-dashboard/blob/master/demo/src/app/my-widget/my-widget.component.ts

There no addWidget method into ngx-dashboard, only on the demo app, you need to call addItem on your dashboard component to add a widget (just to be sure we talk about the same things)

**Comment by anvial** [comment]
Thank You... But I still do not find the error reason.

On first (... and second) look there is no difference in code.

**Comment by jaumard** [comment]
I check and yes doesn't seems to have any differences, the problem may come from somewhere else... Try to run the demo with your widget see if it's ok at least you know for sure it's not this the problem and try searching somewhere else, I don't know maybe angular version or cli version...

**Comment by anvial** [comment]
I try to build demo locally but recieved the error on the last step: 

![image](https://user-images.githubusercontent.com/1950326/28312677-a873ddc2-6bbc-11e7-8637-f88f5dc929b2.png)

**Comment by anvial** [comment]
According to issue topic, 

It could be the problem, that I call addWidget from other (non-AppComponent) Component?

**Comment by anvial** [comment]
... Sorry it's very hard to be an idiot. 

I've the same components names in two pages. 

I fix the path: 
import { TestWidgetComponent } from './components/monitoring-page/widgets/test-widget/test-widget.component';

And I have proper "widget test" (custom widget);
![image](https://user-images.githubusercontent.com/1950326/28314054-c6f3908a-6bc1-11e7-8dc9-e2e3d3f4f88a.png)

Thank You for help.

**Comment by jaumard** [comment]
Cool glad you make it work :) closing this then
