### ISSUE TITLE
Problem with removeItem

### ISSUE THREAD

**Issue by anvial** [jaumard/ngx-dashboard#22]
Hi again,  =)

I think that problem is that `this.dashboard.removeItem(id);` remove not by ID, but the last Item on the dashboard;

I add first widget: 
![image](https://user-images.githubusercontent.com/1950326/28322353-8fc6300a-6bde-11e7-82b0-2a10fa1bdf12.png)
![image](https://user-images.githubusercontent.com/1950326/28322377-9ce4f37a-6bde-11e7-8894-e804e84dd9d3.png)
with ID:
![image](https://user-images.githubusercontent.com/1950326/28322386-a5a2c082-6bde-11e7-85d1-8d5fcbf3d951.png)

Add second widget: 
![image](https://user-images.githubusercontent.com/1950326/28322411-b7520e1e-6bde-11e7-8354-18484385c758.png)
with ID:
![image](https://user-images.githubusercontent.com/1950326/28322432-c32b0718-6bde-11e7-8d54-98a402c1ce95.png)

Then I delete first widget and handler gives me right ID: 
![image](https://user-images.githubusercontent.com/1950326/28322483-e3fa0796-6bde-11e7-9428-467793c0b5a3.png)

But delete LAST Item:
![image](https://user-images.githubusercontent.com/1950326/28322499-f128fae4-6bde-11e7-891b-c6d6e7aec2f9.png)

Then I delete the last widget and I've got the same ID:
![image](https://user-images.githubusercontent.com/1950326/28322535-0a01aa8e-6bdf-11e7-9850-a59ab3c392e3.png)

If I delete from the end, everything as expected.

**Comment by jaumard** [comment]
Sorry remoteItem was pseudo code ^^ the correct methods to remove are 
removeItem(Widget)
removeItemByIndex(index)
removeItemById(id)

**Comment by anvial** [comment]
OK, thanks again!
