### ISSUE TITLE
problem with multiple <dasboard>

### ISSUE THREAD

**Issue by waleed-sarwar** [jaumard/ngx-dashboard#23]
Hi,

is it possible to add multiple "dasboard" tag in a single view. i just tried it but click functionality like close is not working on second one "dashboard" tag

is there any solution please share

![image](https://user-images.githubusercontent.com/30215747/28352684-4d86f556-6c71-11e7-91d9-4e6f28cd43c3.png)

**Comment by jaumard** [comment]
Hello,

Normally it should work, but I never test this :)
Did you reference the second dashboard into your page component ? To call `remove` on the good dashboard component ?

**Comment by waleed-sarwar** [comment]
thanks for quick reply 

one thing that i don't understand how the first dashboard tag is differ to other can you please tell??


![image](https://user-images.githubusercontent.com/30215747/28353950-614cbec6-6c77-11e7-94a8-f903f6b07730.png)

**Comment by jaumard** [comment]
It's just angular stuff, you need to change your html and add #dashboard1 #dashboard2 on your dashboard component and then on your page component you need: 

```
  @ViewChild('dashboard1') dashboard1: DashboardComponent;
  @ViewChild('dashboard2') dashboard2: DashboardComponent;
```

**Comment by waleed-sarwar** [comment]
thanks buddy basically i am new in angular4 thats why .... 
btw it works fine now

**Comment by jaumard** [comment]
No problem :) just want to be sure it's not a problem with this module as I never test multiple dashboard 
Glad it works
