### ISSUE TITLE
disable drag for a specific id 

### ISSUE THREAD

**Issue by waleed-sarwar** [jaumard/ngx-dashboard#26]
hi,
i am using the widget tag and i want to disable the drag functionality for specific widgets is it possible??
the disableDrag() applies on whole dashboard but i want for specific widget

many thanks

**Comment by jaumard** [comment]
It's not possible to disable only one and I don't think it make sense as you can move this widget anyway by moving others around, but I think you can do it by intercepting any mouse/touch event on this widget and stop the propagation, should do the job. I don't think I will implement this into this module.
