### ISSUE TITLE
problem with _onResize function 

### ISSUE THREAD

**Issue by waleed-sarwar** [jaumard/ngx-dashboard#27]
its not working properly

**Comment by jaumard** [comment]
Can you be more precise please ? :D

**Comment by waleed-sarwar** [comment]
when screen reloads see right side margin is not visible... when i change resolution then it fines
![image](https://user-images.githubusercontent.com/30215747/28628587-75131014-723e-11e7-8ad0-6e40a0647818.png)

**Comment by waleed-sarwar** [comment]
also i want to size dynamic but same things happens here although i call this._onResize(null); 
![image](https://user-images.githubusercontent.com/30215747/28636691-5ef48f8c-7258-11e7-9177-24ea10a74614.png)

**Comment by waleed-sarwar** [comment]
same thing in demo 
![image](https://user-images.githubusercontent.com/30215747/28679529-e731ccc0-730c-11e7-8ff2-806787afe4ea.png)

**Comment by jaumard** [comment]
Thanks ! I'll try to reproduce see what append here

**Comment by jaumard** [comment]
I can't manage to reproduce with the demo app ? What are the steps ? 
If I resize the window I have this: 

<img width="524" alt="capture d ecran 2017-07-28 a 15 36 15" src="https://user-images.githubusercontent.com/2970449/28719535-876733b8-73aa-11e7-8205-eb7cebf92cbf.png">

**Comment by waleed-sarwar** [comment]
i just open the demo page 
see right side 
there is no margin/padding on right side
also when i resize the screen it is fixed

![image](https://user-images.githubusercontent.com/30215747/28719628-0fcdd32e-73c4-11e7-9b94-598fd66c2f40.png)

**Comment by jaumard** [comment]
Very strange... Because here is what I've got :(

<img width="1435" alt="capture d ecran 2017-07-28 a 15 40 51" src="https://user-images.githubusercontent.com/2970449/28719706-2b90dbba-73ab-11e7-8d83-c8a340414664.png">

**Comment by waleed-sarwar** [comment]
one question can we paste video here?? i make a video and share it with you

**Comment by jaumard** [comment]
I think github accept any files so I suppose if not you can send me by email

**Comment by waleed-sarwar** [comment]
here is the zip file i attached it
see when i open the (inspect/developer tools) it appears 
[dashboard.zip](https://github.com/jaumard/ngx-dashboard/files/1183206/dashboard.zip)

**Comment by waleed-sarwar** [comment]
the main reason that i noticed is due to scroll bar on right side 
because  if there is no scroll-bar then it works fine

**Comment by jaumard** [comment]
Yeah that was my idea too, maybe it cause some of the sizes I use to be wrong...

**Comment by jaumard** [comment]
Do you have the problem on other browser ?

**Comment by mirwaleed** [comment]
yes i checked in edge also

**Comment by jaumard** [comment]
Edge also has the scroll bar ?

**Comment by mirwaleed** [comment]
yes 
![image](https://user-images.githubusercontent.com/8684488/28744024-918c7d86-7471-11e7-949a-0065ad67976f.png)

**Comment by waleed-sarwar** [comment]
any solution or quick tip to fix it ???

**Comment by jaumard** [comment]
no as I can't reproduce the problem it's difficult to know whatcanbe wrong :( (I have no windows computer). If you can check different things under the `_positionWidget` method, it's there who I set size and position of the widget. I suppose something is wrong there

**Comment by LiamDotPro** [comment]
I'm also having the same issue he mentioned here:

![image](https://user-images.githubusercontent.com/13067327/36374440-4166c486-1563-11e8-9446-688e7c2fa420.png)

windows machine

**Comment by LiamDotPro** [comment]
Okay I fixed it by simply adding the following in an ngAfterViewInit():

`
    ngAfterViewInit(): void {
        this._onResize(null);
    }
`

I will make a PR soon to add this to the demo.
