### ISSUE TITLE
change widgetsize on click function 

### ISSUE THREAD

**Issue by waleed-sarwar** [jaumard/ngx-dashboard#28]
is it possible to change widget size on a click function 
i want to implement the tiles/list view and in list view i need to resize the height of widget 
any suggestions ???

**Comment by jaumard** [comment]
You have the setSize method to resize the widget, just call it whenever you want it should work

**Comment by waleed-sarwar** [comment]
i try out this one but on first time its not work after that it fine.
scenario
 when i click on list view button i update the widget sizes and call this._onResize()

**Comment by waleed-sarwar** [comment]
can you please tell me how to access setSize method ... i use the default widget not a custom one

**Comment by jaumard** [comment]
Check this one https://github.com/jaumard/ngx-dashboard/issues/20 you can access setSize directly from your widget

**Comment by waleed-sarwar** [comment]
yes it works fine by using size function not setSize , i dont know why, maybe i have old version of repo

thanks
