### ISSUE TITLE
Is this an active repo and worth using?

### ISSUE THREAD

**Issue by mharisce** [jaumard/ngx-dashboard#35]
Hi,
I wanted create a dashboard with widget support. My question is that whether this is an active repo and worth using?

**Comment by jaumard** [comment]
It's active :) but need more contributors as I can't do all the needs by myself. And to know if it worth using you should try it see if it fit your needs or not

**Comment by mharisce** [comment]
Thank you for a prompt reply. I have run its demo and I'll try integrating it.

p.s. you can close this thread.
