### ISSUE TITLE
Add Widget button doesn't work properly in the demo

### ISSUE THREAD

**Issue by MichalBzn** [jaumard/ngx-dashboard#36]
Hi,

I've tried to use your demo's button for adding a new widget, and I've noticed that I can't drag the new widget.
Is there any reason for that?
Also when I'm trying to define an app-my-widget in app.component.html file, this widget isn't dragable.
Can you check why?

Thank you,
Michal.

**Comment by sersart** [comment]
Hi, I have same problem. 
Can you please check demo code?
Thanks

**Comment by jaumard** [comment]
Hello,

For demo purpose, dynamic widgets are draggable only from DRAG ME label to show this possibility.
