### ISSUE TITLE
How to set position

### ISSUE THREAD

**Issue by canzy** [jaumard/ngx-dashboard#37]
Hi, 

I see there are 'x' and 'y' values for the widgets in your example, but I don't know how to use them. 
They are not part of your example code. Could you please let me know how to use them.

I want a grid with 9 spaces where I can put one widget in the top left hand corner, and one widget in the bottom hand corner. Can this be done with your component?

Your help would be greatly appreciated.

**Comment by jaumard** [comment]
Hello,

Unfortunately it's not possible with this library, here x and y are manage automatically to have a grid that is dynamic depending of the available size of the screen, you can't place widgets where you want them.
