### ISSUE TITLE
Give access to order attribute with a setter 

### ISSUE THREAD

**Issue by jvalere** [jaumard/ngx-dashboard#40]
Hello
Thanks for your very funny dashboard component.
But we cannot restore a previous widgets order  defined by the user.
Actually the attribute "order" is "readonly", a setter or another way will be great.

Thanks

**Comment by jaumard** [comment]
Hello, the order depending only on the order of addition into the dashboard, so to restore the order, just add your widgets under the dashboard on the order to restore, no need more

**Comment by jvalere** [comment]
Ok but if i understood correctly the api addItem, i am obliged to define a specific Widget Angular Component for each widget that i want to instantiate into the dashboard.
I would use a widgets list defined by tags into the html source of the dashboard and let it instantiate them. I had not defined a specific widget component for each of them.
After retrieve the order defined by the user I would restore it by any way you can suggest to me.
I can retieve the widgets collection with your getWidgetById api but i cannot restore it after clearing because addItem requires a Angular component as parameter.
But perhaps I make a mistake in understanding.

**Comment by jvalere** [comment]
I solve the problem with dynamic widget content
Thanks
