### ISSUE TITLE
Improve drag on touch device

### ISSUE THREAD

**Issue by jaumard** [jaumard/ngx-dashboard#5]
On touch device the item doesn't follow the finger, it's above it, sometime a lot above... I think the calculation is wrong at some point...

**Comment by nadir35** [comment]
Worked for me: 
Replace in dashboard.component.js ._getOffsetFromTarget(e)

>   e = e.touches.length > 0 ? e.touches[0] : e.changedTouches[0];
>             x = e.pageX - e.target.offsetLeft;
>             y = e.pageY - e.target.offsetTop;

with 
   

>         e = e.touches.length > 0 ? e.touches[0] : e.changedTouches[0];
>             var rect =e.target.getBoundingClientRect();
>             x = e.pageX - rect.left;
>             y = e.pageY - rect.top;

*Update*
While this works on the starting page of the dashboard, the bug still occurs on mobile devices for widgets that appear beyond the immediate view. So if you have a dashboard and add many widgets to it, widgets that are created beyond the initial view still have buggy dragging.

**Comment by jaumard** [comment]
Does it still work on desktop after that ? Because when I tried (not this ^^) to fix this issue only one was working at the same time.
I'll test this tonight when I'm back home :) thanks !

**Comment by nadir35** [comment]
Yes, since for the Desktop version the else{} part of the If-Else applies.

**Comment by jaumard** [comment]
Cool :) I didn't check the code yet ^^ I'll try and let you know 
If it's work I'll push it for next release :D

**Comment by jaumard** [comment]
@nadir35 I try on Android with chrome/firefox and it's even worse than the actual code, the widget is mainly out of the screen with this code :(

**Comment by nadir35** [comment]
I just tried it with Android + Chrome too and didn't notice any weird behaviour in vertical mode. In horizontal mode however, the problem still persists. I do not notice that it is worse than the current code though. I will continue to look for the right calculation.

Here the function again in case there were some misunderstandings:

>     DashboardComponent.prototype._getOffsetFromTarget = function (e) {
>         var x;
>         var y;
>         if (this._isTouchEvent(e)) {
>             e = e.touches.length > 0 ? e.touches[0] : e.changedTouches[0];
>             var rect =e.target.getBoundingClientRect();
>             x = e.pageX - rect.left;
>             y = e.pageY - rect.top;
>         }
>         else {
>             x = e.offsetX || e.offsetLeft;
>             y = e.offsetY || e.offsetTop;
>         }
>         return { top: y, left: x };
>     };

**Comment by jaumard** [comment]
No misunderstood I modify this one, on only test vertically. On the current solution my widget is 1 time above the correct solution, with your solution and when I move a widget from the bottom (last one for example) it just disappear and go to the top of the dashboard :(

**Comment by nadir35** [comment]
Yes, I made an update to my comment but I guess github didn't notify:

> Update
While this works on the starting page of the dashboard, the bug still occurs on mobile devices for widgets that appear beyond the immediate view. So if you have a dashboard and add many widgets to it, widgets that are created beyond the initial view still have buggy dragging.

So did you mean with "from the bottom" a widget that was created down below so you had to scroll? If yes then I noticed that too.

**Comment by jaumard** [comment]
Ho didn't see that sorry :) yeah I'm talking about last widget when you scroll. But with your solution we just can't drag anymore widget once scrolled where the current solution still work, at least it's still useable ^^

**Comment by nadir35** [comment]
I fixed the scrolling issue, I think.
The new function looks like this:

>
>      DashboardComponent.prototype._getOffsetFromTarget = function (e) {
>         var x;
>         var y;
>         var scrollOffset =0;
>         if (this._isTouchEvent(e)) {
>             e = e.touches.length > 0 ? e.touches[0] : e.changedTouches[0];
>             var rect =e.target.getBoundingClientRect();
>             x = e.pageX - rect.left;
>             y = e.pageY - rect.top;
>             scrollOffset = ($(window).scrollTop() || $("body").scrollTop());
>         }
>         else {
>             x = e.offsetX || e.offsetLeft;
>             y = e.offsetY || e.offsetTop;
>         }
>         return { top: y-scrollOffset, left: x };
>     };

Can you try it out?

**Comment by jaumard** [comment]
Hum it will not work like this because of `$` I think, are you using jQuery ? Don't think `$` is part of angular, I need to translate this into angular way. But look promising I'll try to test it asap thanks!

**Comment by nadir35** [comment]
Yes I have jQuery in my index.html, didn't even think of that...

**Comment by nadir35** [comment]
Alternative without jQuery:

>             scrollOffset= document.body.scrollTop;

**Comment by jaumard** [comment]
Look fixed ! Nice ! Thanks ! I'll push it to master later when I'm home ^^
