### ISSUE TITLE
add angular 2 AOT compatibility with last angular-cli version 

### ISSUE THREAD

**Issue by jaumard** [jaumard/ngx-dashboard#6]
If you can help @valorkin that would be amazing :) let me know if you have time

**Comment by valorkin** [comment]
Hopefully I will have some time today

**Comment by jaumard** [comment]
My test for updating the libraries is under update_cli branch https://github.com/jaumard/ng2-dashboard/tree/update_cli

**Comment by jaumard** [comment]
@valorkin I made some move on this with some help from a contributor ^^ and I think it's very close to be done. I have one error left : 

```
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/jaumard/LISAProjects/lisa-ui/node_modules/ng2-dashboard/node_modules/@angular/core/core.d.ts, resolving symbol Ng2DashboardModule in /Users/jaumard/LISAProjects/lisa-ui/node_modules/ng2-dashboard/components/index.ts, resolving symbol Ng2DashboardModule in /Users/jaumard/LISAProjects/lisa-ui/node_modules/ng2-dashboard/components/index.ts
webpack
```

I think it's related to AOT, maybe the way I use the library or the way I deploy it. Can you help with this ?

**Comment by jaumard** [comment]
Should be ok now on 1.0.4
